DECLARE @sql NVARCHAR(max)='',@pql NVARCHAR(max)=''

SELECT @sql += ' Drop table ' + QUOTENAME(TABLE_SCHEMA) + '.'+ QUOTENAME(TABLE_NAME) + '; '
FROM   INFORMATION_SCHEMA.TABLES
WHERE  TABLE_TYPE = 'BASE TABLE'
PRINT @sql
--Exec Sp_executesql @sql
PRINT ''

SELECT @pql += 'ALTER TABLE ' + TABLE_NAME +    ' DROP CONSTRAINT ' + CONSTRAINT_NAME + ';'
FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE

PRINT @pql
--EXEC sp_executesql @sql2;
