SELECT ROUTINE_NAME, ROUTINE_DEFINITION
    FROM INFORMATION_SCHEMA.ROUTINES 
    WHERE ROUTINE_DEFINITION LIKE '%CLIENT_OCCUPATION_CODE%'  OR  ROUTINE_DEFINITION LIKE '%OCC_TYPE%' 
    AND ROUTINE_TYPE='PROCEDURE'
